export const config = {
  baseUrl: __ENV.BASE_URL || 'http://127.0.0.1:18080',
  issueRequestSyntheticUserIdBase: Number(__ENV.ISSUE_REQUEST_SYNTHETIC_USER_ID_BASE || 1_000_000),
  adminName: __ENV.ADMIN_NAME || 'Load Test Admin',
  adminEmail: __ENV.ADMIN_EMAIL || 'loadtest-admin@coupon.local',
  adminPassword: __ENV.ADMIN_PASSWORD || 'admin1234!',
  testUserPassword: __ENV.TEST_USER_PASSWORD || 'coupon1234!',
  startupTimeoutSeconds: Number(__ENV.STARTUP_TIMEOUT_SECONDS || 60),
  startupPollIntervalSeconds: Number(__ENV.STARTUP_POLL_INTERVAL_SECONDS || 1),
  smokeVus: Number(__ENV.SMOKE_VUS || 1),
  issueRequestSmokeVus: Number(__ENV.ISSUE_REQUEST_SMOKE_VUS || 1),
  baselineVus: Number(__ENV.BASELINE_VUS || 20),
  baselineDuration: __ENV.BASELINE_DURATION || '10m',
  baselineSessionPoolSize: Number(__ENV.BASELINE_SESSION_POOL_SIZE || 100),
  baselineCouponPoolSize: Number(__ENV.BASELINE_COUPON_POOL_SIZE || 10),
  issueBurstVus: Number(__ENV.ISSUE_BURST_VUS || 1000),
  issueBurstStock: Number(
    __ENV.ISSUE_BURST_STOCK || __ENV.ISSUE_BURST_VUS || 1000,
  ),
  issueBurstMaxDuration: __ENV.ISSUE_BURST_MAX_DURATION || '5m',
  issueBurstSetupTimeout: __ENV.ISSUE_BURST_SETUP_TIMEOUT || '20m',
  issueBurstLockRetryCount: Number(__ENV.ISSUE_BURST_LOCK_RETRY_COUNT || 3),
  issueBurstLockRetryDelayMs: Number(__ENV.ISSUE_BURST_LOCK_RETRY_DELAY_MS || 250),
  slowRequestSampleLimit: Number(__ENV.SLOW_REQUEST_SAMPLE_LIMIT || 10),
  slowRequestPreviewMaxLength: Number(__ENV.SLOW_REQUEST_PREVIEW_MAX_LENGTH || 300),
  slowRequestSampleStdout: __ENV.SLOW_REQUEST_SAMPLE_STDOUT === '1',
  issueOverloadVus: Number(__ENV.ISSUE_OVERLOAD_VUS || 100),
  issueOverloadDuration: __ENV.ISSUE_OVERLOAD_DURATION || '10m',
  issueOverloadUserPoolSize: Number(
    __ENV.ISSUE_OVERLOAD_USER_POOL_SIZE ||
      Math.max(Number(__ENV.ISSUE_OVERLOAD_VUS || 100) * 2, 200),
  ),
  issueOverloadCouponPoolSize: Number(__ENV.ISSUE_OVERLOAD_COUPON_POOL_SIZE || 500),
  issueOverloadSetupTimeout: __ENV.ISSUE_OVERLOAD_SETUP_TIMEOUT || '10m',
  issueRequestPollTimeoutSeconds: Number(__ENV.ISSUE_REQUEST_POLL_TIMEOUT_SECONDS || 30),
  issueRequestPollIntervalMs: Number(__ENV.ISSUE_REQUEST_POLL_INTERVAL_MS || 500),
  issueRequestBurstVus: Number(__ENV.ISSUE_REQUEST_BURST_VUS || 1000),
  issueRequestBurstStock: Number(
    __ENV.ISSUE_REQUEST_BURST_STOCK || __ENV.ISSUE_REQUEST_BURST_VUS || 1000,
  ),
  issueRequestBurstMaxDuration: __ENV.ISSUE_REQUEST_BURST_MAX_DURATION || '10m',
  issueRequestBurstSetupTimeout: __ENV.ISSUE_REQUEST_BURST_SETUP_TIMEOUT || '20m',
  issueRequestOverloadVus: Number(__ENV.ISSUE_REQUEST_OVERLOAD_VUS || 50),
  issueRequestOverloadDuration: __ENV.ISSUE_REQUEST_OVERLOAD_DURATION || '10m',
  issueRequestOverloadCouponPoolSize: Number(
    __ENV.ISSUE_REQUEST_OVERLOAD_COUPON_POOL_SIZE || 200,
  ),
  issueRequestOverloadUserPoolSize: Number(
    __ENV.ISSUE_REQUEST_OVERLOAD_USER_POOL_SIZE ||
      Math.max(Number(__ENV.ISSUE_REQUEST_OVERLOAD_VUS || 50) * 200, 10000),
  ),
  issueRequestOverloadStockPerCoupon: Number(
    __ENV.ISSUE_REQUEST_OVERLOAD_STOCK_PER_COUPON || 100000,
  ),
  issueRequestOverloadSetupTimeout: __ENV.ISSUE_REQUEST_OVERLOAD_SETUP_TIMEOUT || '15m',
  issueRequestRampGracefulStop: __ENV.ISSUE_REQUEST_RAMP_GRACEFUL_STOP || '30s',
  issueRequestRampStock: Number(__ENV.ISSUE_REQUEST_RAMP_STOCK || 10000000),
  issueRequestRampUserPoolSize: Number(
    __ENV.ISSUE_REQUEST_RAMP_USER_POOL_SIZE ||
      Math.max(
        Number(__ENV.ISSUE_REQUEST_RAMP_STAGE1_TARGET || 3000),
        Number(__ENV.ISSUE_REQUEST_RAMP_STAGE2_TARGET || 3000),
        Number(__ENV.ISSUE_REQUEST_RAMP_STAGE3_TARGET || 5000),
        Number(__ENV.ISSUE_REQUEST_RAMP_STAGE4_TARGET || 5000),
        Number(__ENV.ISSUE_REQUEST_RAMP_STAGE5_TARGET || 7000),
        Number(__ENV.ISSUE_REQUEST_RAMP_STAGE6_TARGET || 7000),
      ),
  ),
  issueRequestRampCouponPoolSize: Number(__ENV.ISSUE_REQUEST_RAMP_COUPON_POOL_SIZE || 1000),
  issueRequestRampStockPerCoupon: Number(__ENV.ISSUE_REQUEST_RAMP_STOCK_PER_COUPON || 100000),
  issueRequestRampStage1Duration: __ENV.ISSUE_REQUEST_RAMP_STAGE1_DURATION || '3m',
  issueRequestRampStage1Target: Number(__ENV.ISSUE_REQUEST_RAMP_STAGE1_TARGET || 3000),
  issueRequestRampStage2Duration: __ENV.ISSUE_REQUEST_RAMP_STAGE2_DURATION || '1m',
  issueRequestRampStage2Target: Number(__ENV.ISSUE_REQUEST_RAMP_STAGE2_TARGET || 3000),
  issueRequestRampStage3Duration: __ENV.ISSUE_REQUEST_RAMP_STAGE3_DURATION || '2m',
  issueRequestRampStage3Target: Number(__ENV.ISSUE_REQUEST_RAMP_STAGE3_TARGET || 5000),
  issueRequestRampStage4Duration: __ENV.ISSUE_REQUEST_RAMP_STAGE4_DURATION || '3m',
  issueRequestRampStage4Target: Number(__ENV.ISSUE_REQUEST_RAMP_STAGE4_TARGET || 5000),
  issueRequestRampStage5Duration: __ENV.ISSUE_REQUEST_RAMP_STAGE5_DURATION || '2m',
  issueRequestRampStage5Target: Number(__ENV.ISSUE_REQUEST_RAMP_STAGE5_TARGET || 7000),
  issueRequestRampStage6Duration: __ENV.ISSUE_REQUEST_RAMP_STAGE6_DURATION || '5m',
  issueRequestRampStage6Target: Number(__ENV.ISSUE_REQUEST_RAMP_STAGE6_TARGET || 7000),
  issueRequestRampStage7Duration: __ENV.ISSUE_REQUEST_RAMP_STAGE7_DURATION || '3m',
  issueRequestRampStage7Target: Number(__ENV.ISSUE_REQUEST_RAMP_STAGE7_TARGET || 0),
  issueRequestRealRampUserPoolSize: Number(__ENV.ISSUE_REQUEST_REAL_RAMP_USER_POOL_SIZE || 7000),
  issueRequestRealRampCouponPoolSize: Number(__ENV.ISSUE_REQUEST_REAL_RAMP_COUPON_POOL_SIZE || 1000),
  issueRequestRealRampStockPerCoupon: Number(
    __ENV.ISSUE_REQUEST_REAL_RAMP_STOCK_PER_COUPON || 100000,
  ),
  issueRequestRealRampSetupTimeout: __ENV.ISSUE_REQUEST_REAL_RAMP_SETUP_TIMEOUT || '30m',
  contentionVus: Number(__ENV.CONTENTION_VUS || 100),
  contentionMaxDuration: __ENV.CONTENTION_MAX_DURATION || '2m',
  resultsDir: __ENV.RESULTS_DIR || 'load-test/k6/results',
};
