spring.application.name: coupon-system
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:local}

spring:
  config:
    import:
      - db-core.yml
      - redis.yml
      - authentication.yml
      - swagger.yml
      - logging.yml
      - monitoring.yml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  web.resources.add-mappings: false
  servlet:
    encoding:
      charset: UTF-8

api:
  kafka:
    coupon-issue:
      enabled: true
      topic: coupon.issue.v1
      ack-timeout: 10s
      topic-partitions: 3
      topic-replicas: 1

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
