services:
  # 기본 로컬 실행용 진입점입니다.
  mysql:
    extends:
      file: docker-compose.infrastructure.yml
      service: mysql

  redis:
    extends:
      file: docker-compose.infrastructure.yml
      service: redis

  kafka:
    extends:
      file: docker-compose.infrastructure.yml
      service: kafka

  kafka-ui:
    extends:
      file: docker-compose.infrastructure.yml
      service: kafka-ui

  coupon-app:
    extends:
      file: docker-compose.runtime.yml
      service: coupon-app

  coupon-worker:
    extends:
      file: docker-compose.runtime.yml
      service: coupon-worker

volumes:
  mysql_data:
  redis_data:
  kafka_data:
