spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/local
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

datasource:
  db:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ""
      pool-name: core-db-pool
      maximum-pool-size: 5
      data-source-properties:
        rewriteBatchedStatements: true
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

datasource:
  db:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ""
      pool-name: core-db-pool
      maximum-pool-size: 5
      data-source-properties:
        rewriteBatchedStatements: true
---
spring:
  config:
    activate:
      on-profile: "!local & !test"

datasource:
  db:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DATASOURCE_DB_CORE_JDBC_URL:jdbc:mysql://localhost:3306/coupon-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
      username: ${DATASOURCE_DB_CORE_USERNAME:coupon-admin}
      password: ${DATASOURCE_DB_CORE_PASSWORD:coupon!@#}
      pool-name: core-db-pool
      maximum-pool-size: 10
      connection-timeout: 1500
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
