spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

datasource:
  db:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password: ""
      pool-name: core-db-pool
      maximum-pool-size: 5
      data-source-properties:
        rewriteBatchedStatements: true
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_log: true
        format_sql: true
datasource:
  db:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${DATASOURCE_DB_CORE_JDBC_URL:jdbc:postgresql://localhost:5432/studio_xid}
      username: ${DATASOURCE_DB_CORE_USERNAME:postgres}
      password: ${DATASOURCE_DB_CORE_PASSWORD:postgres}
      pool-name: core-db-pool
      maximum-pool-size: 10
      connection-timeout: 1500
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      data-source-properties:
        rewriteBatchedStatements: true
