apiVersion: 1

datasources:
  - name: k6-influxdb
    uid: k6_influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      dbName: myk6db
      httpMode: GET
